<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\BatterySubmit;

/**
 * BatterySubmitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatterySubmitRepository extends EntityRepository
{
  public function findAllCountByType()
    {

      $em = $this->getEntityManager();

//todo: $qb = $this->createQueryBuilder('bs');  -- then 1 lines are not needed: to get entity manager and "from" statement
      $qb = $em->createQueryBuilder()
               ->select('sum(bs.count) AS total', 'bs.type')
               ->groupBy('bs.type')
               ->from(BatterySubmit::class, 'bs')
               ->orderBy('bs.type', 'ASC');

      return $qb->getQuery()->getResult();

    }
}
